/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Cliente;
import controller.Venda;
import java.text.Normalizer;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.ClienteDAO;
import model.VendaDAO;

/**
 *
 * @author gustavo
 */
public class AtribuirVendaPrazo extends javax.swing.JFrame {

    Venda vendaTemp = new Venda();
    CadastrarVenda cadastrarVendaTemp;

    /**
     * Creates new form NovaVendaPrazo
     */
    public AtribuirVendaPrazo(CadastrarVenda cadastrarVendaTemp, Venda vendaTemp) {
        initComponents();
        this.vendaTemp = vendaTemp;
        this.mostrarTodosClientes();
        this.setLocationRelativeTo(null);
        this.cadastrarVendaTemp = cadastrarVendaTemp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_cliente = new javax.swing.JLabel();
        txt_filtrar = new javax.swing.JTextField();
        btn_novoCliente = new javax.swing.JButton();
        btn_filtarClientes = new javax.swing.JButton();
        btn_atribuirVendaPrazo = new javax.swing.JButton();
        cb_listaClientes = new javax.swing.JComboBox<>();
        btn_mostrarTodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(234, 211, 161));

        lbl_cliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_cliente.setText("Cliente");

        txt_filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filtrarActionPerformed(evt);
            }
        });

        btn_novoCliente.setText("Novo Cliente");
        btn_novoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoClienteActionPerformed(evt);
            }
        });

        btn_filtarClientes.setText("Filtrar");
        btn_filtarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filtarClientesActionPerformed(evt);
            }
        });

        btn_atribuirVendaPrazo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_atribuirVendaPrazo.setText("Atribuir Venda");
        btn_atribuirVendaPrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atribuirVendaPrazoActionPerformed(evt);
            }
        });

        cb_listaClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        btn_mostrarTodos.setText("Mostrar Todos");
        btn_mostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cliente)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btn_atribuirVendaPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_filtarClientes))
                            .addComponent(cb_listaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_novoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(btn_mostrarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_filtarClientes)
                    .addComponent(btn_mostrarTodos))
                .addGap(22, 22, 22)
                .addComponent(lbl_cliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_listaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_novoCliente))
                .addGap(22, 22, 22)
                .addComponent(btn_atribuirVendaPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_novoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoClienteActionPerformed
        CadastroCliente cadastroCliente = new CadastroCliente();
        cadastroCliente.setVisible(true);
    }//GEN-LAST:event_btn_novoClienteActionPerformed

    private void btn_atribuirVendaPrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atribuirVendaPrazoActionPerformed
        VendaDAO daoVenda = new VendaDAO();
        String nomeCliente = cb_listaClientes.getSelectedItem().toString();
        if(daoVenda.atribuirVendaPrazo(this.vendaTemp, nomeCliente)){
            JOptionPane.showMessageDialog(null, "Venda Atribuída à\n"
                    + nomeCliente);
            this.dispose();
            this.cadastrarVendaTemp.dispose();
        }
    }//GEN-LAST:event_btn_atribuirVendaPrazoActionPerformed

    private void txt_filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filtrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filtrarActionPerformed

    private void btn_filtarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filtarClientesActionPerformed
        cb_listaClientes.removeAllItems();
        this.filtarClientes();
    }//GEN-LAST:event_btn_filtarClientesActionPerformed

    private void btn_mostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarTodosActionPerformed
        this.mostrarTodosClientes();
    }//GEN-LAST:event_btn_mostrarTodosActionPerformed

    public void mostrarTodosClientes() {
        cb_listaClientes.removeAllItems();
        ClienteDAO daoCliente = new ClienteDAO();
        for (Cliente cliente : daoCliente.listaClientes()) {
            cb_listaClientes.addItem(cliente.getNome());
        }

        btn_mostrarTodos.setVisible(false);
    }

    public void filtarClientes() {
        ClienteDAO daoCliente = new ClienteDAO();

        for (Cliente cliente : daoCliente.listaClientes()) {
            String str1 = this.formataStringComp(cliente.getNome());
            String str2 = this.formataStringComp(txt_filtrar.getText());
            if (str1.contains(str2)) {
                cb_listaClientes.addItem(cliente.getNome());
            }
        }

        btn_mostrarTodos.setVisible(true);
    }

    private String formataStringComp(String str) {
        str = this.removerAcentos(str.toLowerCase());
        return str;
    }

    private static String removerAcentos(String str) {
        str = Normalizer.normalize(str, Normalizer.Form.NFD);
        str = str.replaceAll("[^\\p{ASCII}]", "");
        return str;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atribuirVendaPrazo;
    private javax.swing.JButton btn_filtarClientes;
    private javax.swing.JButton btn_mostrarTodos;
    private javax.swing.JButton btn_novoCliente;
    private javax.swing.JComboBox<String> cb_listaClientes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_cliente;
    private javax.swing.JTextField txt_filtrar;
    // End of variables declaration//GEN-END:variables
}
