/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Produto;
import controller.Venda;
import java.text.DecimalFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ProdutoDAO;
import model.VendaDAO;

/**
 *
 * @author gustavo
 */
public class CadastrarVenda extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarVenda
     */
    public CadastrarVenda() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_codigoProduto = new javax.swing.JTextField();
        lbl_codigoProduto = new javax.swing.JLabel();
        btn_adicionarProduto = new javax.swing.JButton();
        btn_CadastrarVenda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_vendas = new javax.swing.JTable();
        txt_quantidade = new javax.swing.JTextField();
        lbl_quantidade = new javax.swing.JLabel();
        txt_porcDesconto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbl_txtValorFix = new javax.swing.JLabel();
        btn_excluirProduto = new javax.swing.JButton();
        btn_aplicarDesconto = new javax.swing.JButton();
        lbl_txtValorDescontoFix = new javax.swing.JLabel();
        lbl_txtValorFinalFix = new javax.swing.JLabel();
        lbl_txtValorFinalVar = new javax.swing.JLabel();
        lbl_txtValorVar = new javax.swing.JLabel();
        lbl_txtValorDescontoVar = new javax.swing.JLabel();
        btn_removerDesconto = new javax.swing.JButton();
        check_vendaPrazo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(234, 211, 161));

        txt_codigoProduto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_codigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoProdutoActionPerformed(evt);
            }
        });

        lbl_codigoProduto.setText("Código Produto");

        btn_adicionarProduto.setText("Adicionar Produto");
        btn_adicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarProdutoActionPerformed(evt);
            }
        });

        btn_CadastrarVenda.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_CadastrarVenda.setText("Cadastrar Venda");
        btn_CadastrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarVendaActionPerformed(evt);
            }
        });

        tbl_vendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço", "Quantidade", "Código"
            }
        ));
        tbl_vendas.setSelectionBackground(new java.awt.Color(255, 102, 102));
        jScrollPane1.setViewportView(tbl_vendas);

        txt_quantidade.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_quantidade.setText("1");
        txt_quantidade.setMinimumSize(new java.awt.Dimension(15, 22));
        txt_quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_quantidadeActionPerformed(evt);
            }
        });

        lbl_quantidade.setText("Quantidade");

        txt_porcDesconto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_porcDesconto.setText("0");

        jLabel3.setText("%");

        lbl_txtValorFix.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_txtValorFix.setText("Valor: R$");

        btn_excluirProduto.setText("Excluir Produto");
        btn_excluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirProdutoActionPerformed(evt);
            }
        });

        btn_aplicarDesconto.setText("Aplicar Desconto");
        btn_aplicarDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aplicarDescontoActionPerformed(evt);
            }
        });

        lbl_txtValorDescontoFix.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_txtValorDescontoFix.setText("Desconto: R$");

        lbl_txtValorFinalFix.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_txtValorFinalFix.setText("Valor Final: R$");

        lbl_txtValorFinalVar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_txtValorFinalVar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_txtValorFinalVar.setText("0,00");

        lbl_txtValorVar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_txtValorVar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_txtValorVar.setText("0,00");

        lbl_txtValorDescontoVar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_txtValorDescontoVar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_txtValorDescontoVar.setText("0,00");

        btn_removerDesconto.setText("Remover Desconto");
        btn_removerDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removerDescontoActionPerformed(evt);
            }
        });

        check_vendaPrazo.setBackground(new java.awt.Color(234, 211, 161));
        check_vendaPrazo.setText("Venda À Prazo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_codigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_codigoProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_quantidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_quantidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_excluirProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_adicionarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_txtValorFix)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_txtValorVar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_porcDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_txtValorFinalFix)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_txtValorFinalVar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(check_vendaPrazo)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btn_removerDesconto)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btn_aplicarDesconto)
                                            .addGap(26, 26, 26)
                                            .addComponent(lbl_txtValorDescontoFix, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbl_txtValorDescontoVar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(10, 10, 10))
                                .addComponent(btn_CadastrarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_quantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_adicionarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_excluirProduto)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_codigoProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_codigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_txtValorFix)
                    .addComponent(lbl_txtValorVar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_txtValorDescontoFix)
                        .addComponent(lbl_txtValorDescontoVar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_porcDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(btn_aplicarDesconto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_removerDesconto)
                .addGap(28, 28, 28)
                .addComponent(check_vendaPrazo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CadastrarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_txtValorFinalVar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_txtValorFinalFix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoProdutoActionPerformed

    private void txt_quantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_quantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_quantidadeActionPerformed

    private void btn_CadastrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarVendaActionPerformed

        if(!check_vendaPrazo.isSelected()){
            this.cadastrarVenda();
        } else{
            AtribuirVendaPrazo atribuirVendaPrazo = new AtribuirVendaPrazo(this.construtorVenda());
            atribuirVendaPrazo.setVisible(true);
        }

    }//GEN-LAST:event_btn_CadastrarVendaActionPerformed

    private void btn_adicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarProdutoActionPerformed
        ProdutoDAO daoProduto = new ProdutoDAO();
        DefaultTableModel dtmVendas = (DefaultTableModel) tbl_vendas.getModel();
        long codigo = Long.parseLong(txt_codigoProduto.getText());
        int quantidade = Integer.parseInt(txt_quantidade.getText());
        double valorVenda = 0;

        Produto produto = daoProduto.getInfoProduto(codigo);

        Object[] dados = {
            produto.getNomeProduto(),
            produto.getPreco(),
            quantidade,
            codigo
        };

        dtmVendas.addRow(dados);

        for (int i = 0; i < tbl_vendas.getRowCount(); i++) {

            double precoLinha = (double) tbl_vendas.getModel().getValueAt(i, 1);
            int qtdLinha = (int) tbl_vendas.getModel().getValueAt(i, 2);
            double valorLinha = precoLinha * (double) qtdLinha;

            valorVenda += valorLinha;
        }

        String strValorVenda = String.format("%.2f", valorVenda);
        lbl_txtValorVar.setText(strValorVenda);
        txt_quantidade.setText("1");
        this.atualizaVendaFinal();
    }//GEN-LAST:event_btn_adicionarProdutoActionPerformed

    private void btn_excluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirProdutoActionPerformed
        if (tbl_vendas.getSelectedRow() != -1) {
            double valorVenda = 0;
            DefaultTableModel dtmEquipes = (DefaultTableModel) tbl_vendas.getModel();
            dtmEquipes.removeRow(tbl_vendas.getSelectedRow());

            for (int i = 0; i < tbl_vendas.getRowCount(); i++) {

                double precoLinha = (double) tbl_vendas.getModel().getValueAt(i, 1);
                int qtdLinha = (int) tbl_vendas.getModel().getValueAt(i, 2);
                double valorLinha = precoLinha * (double) qtdLinha;

                valorVenda += valorLinha;
            }

            String strValorVenda = String.format("%.2f", valorVenda);
            lbl_txtValorVar.setText(strValorVenda);
            this.atualizaVendaFinal();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir");
        }
    }//GEN-LAST:event_btn_excluirProdutoActionPerformed

    private void btn_aplicarDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aplicarDescontoActionPerformed

        this.atualizaVendaFinal();

    }//GEN-LAST:event_btn_aplicarDescontoActionPerformed

    private void btn_removerDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removerDescontoActionPerformed
        txt_porcDesconto.setText("0");
        this.atualizaVendaFinal();
    }//GEN-LAST:event_btn_removerDescontoActionPerformed
    
    private Venda construtorVenda(){
        double valorVendaFinal = Double.parseDouble(lbl_txtValorFinalVar.getText().replace(",", "."));
        long millis = System.currentTimeMillis();
        java.sql.Date dataVenda = new java.sql.Date(millis);

        Venda venda = new Venda(valorVendaFinal, dataVenda);
        return venda;
    }
    private void cadastrarVenda(){
        //inserindo a venda no banco de dados
        Venda venda = this.construtorVenda();
        boolean vendaOk = true;
        VendaDAO daoVenda = new VendaDAO();

        //atualizando o estoque de cada produto
        for (int i = 0; i < tbl_vendas.getRowCount(); i++) {

            int qtdLinha = (int) tbl_vendas.getModel().getValueAt(i, 2);
            long codigoProduto = (long) tbl_vendas.getModel().getValueAt(i, 3);
            ProdutoDAO daoProduto = new ProdutoDAO();
            if (daoProduto.getEstoqueProduto(codigoProduto) < qtdLinha) {
                vendaOk = false;
            }
        }

        if (vendaOk) {
            for (int i = 0; i < tbl_vendas.getRowCount(); i++) {
                int qtdLinha = (int) tbl_vendas.getModel().getValueAt(i, 2);
                long codigoProduto = (long) tbl_vendas.getModel().getValueAt(i, 3);
                ProdutoDAO daoProduto = new ProdutoDAO();
                daoProduto.removerEstoqueProduto(qtdLinha, codigoProduto);
            }
            if (daoVenda.inserirNovaVenda(venda)) {
                JOptionPane.showMessageDialog(null, "Venda Confirmada.");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Algum dos produtos que você está tentando vender não tem estoque!\n Por favor verifique!");
        }
    }
    
    /**
     * Esta função atualiza a lbl com o valor final da venda.
     */
    private void atualizaVendaFinal() {

        double valorVenda = Double.parseDouble(lbl_txtValorVar.getText().replace(",", "."));
        double porcDesconto = Double.parseDouble(txt_porcDesconto.getText());
        double valorDesconto = valorVenda * (porcDesconto / 100);
        String strValorDesconto = String.format("%.2f", valorDesconto);
        lbl_txtValorDescontoVar.setText(strValorDesconto);
        double valorFinal = valorVenda - valorDesconto;
        String strValorFinal = String.format("%.2f", valorFinal);
        lbl_txtValorFinalVar.setText(strValorFinal);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CadastrarVenda;
    private javax.swing.JButton btn_adicionarProduto;
    private javax.swing.JButton btn_aplicarDesconto;
    private javax.swing.JButton btn_excluirProduto;
    private javax.swing.JButton btn_removerDesconto;
    private javax.swing.JCheckBox check_vendaPrazo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_codigoProduto;
    private javax.swing.JLabel lbl_quantidade;
    private javax.swing.JLabel lbl_txtValorDescontoFix;
    private javax.swing.JLabel lbl_txtValorDescontoVar;
    private javax.swing.JLabel lbl_txtValorFinalFix;
    private javax.swing.JLabel lbl_txtValorFinalVar;
    private javax.swing.JLabel lbl_txtValorFix;
    private javax.swing.JLabel lbl_txtValorVar;
    private javax.swing.JTable tbl_vendas;
    private javax.swing.JTextField txt_codigoProduto;
    private javax.swing.JTextField txt_porcDesconto;
    private javax.swing.JTextField txt_quantidade;
    // End of variables declaration//GEN-END:variables
}
