/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Produto;
import javax.swing.JOptionPane;
import model.ProdutoDAO;

/**
 *
 * @author gustavo
 */
public class InserirEstoqueProduto extends javax.swing.JFrame {

    /**
     * Creates new form InserirEstoqueProduto
     */
    public InserirEstoqueProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_inserirEstoque = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_codigoProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_addEstoque = new javax.swing.JFormattedTextField();
        btn_mostraInfo = new javax.swing.JButton();
        lbl_nome = new javax.swing.JLabel();
        lbl_preco = new javax.swing.JLabel();
        lbl_qtdEstoque = new javax.swing.JLabel();

        jLabel2.setText("Quantidade");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir Estoque");

        jPanel1.setBackground(new java.awt.Color(234, 211, 161));
        jPanel1.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N

        btn_inserirEstoque.setText("Inserir Estoque");
        btn_inserirEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inserirEstoqueActionPerformed(evt);
            }
        });

        jLabel1.setText("Código do Produto");

        txt_codigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoProdutoActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantidade");

        txt_addEstoque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txt_addEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addEstoqueActionPerformed(evt);
            }
        });

        btn_mostraInfo.setText("Mostrar Informações do Produto");
        btn_mostraInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostraInfoActionPerformed(evt);
            }
        });

        lbl_nome.setText("Nome: ");

        lbl_preco.setText("Preço:");

        lbl_qtdEstoque.setText("Quantidade em Estoque Atual:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(txt_codigoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(txt_addEstoque)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btn_inserirEstoque)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_mostraInfo)
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_preco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_qtdEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_codigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_mostraInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_nome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_preco)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_qtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_addEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btn_inserirEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_addEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addEstoqueActionPerformed

    private void btn_inserirEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inserirEstoqueActionPerformed
        // TODO add your handling code here:
        if (!txt_codigoProduto.getText().isEmpty() && !txt_addEstoque.getText().isEmpty()) {
            ProdutoDAO daoProduto = new ProdutoDAO();
            int codigo = Integer.parseInt(txt_codigoProduto.getText());
            int addEstoque = Integer.parseInt(txt_addEstoque.getText());
            if (daoProduto.inserirEstoqueProduto(addEstoque, codigo)) {
                JOptionPane.showMessageDialog(null, "Estoque Inserido");
                this.btn_mostraInfoActionPerformed(evt);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Todos os campos devem estar preenchidos.");
        }

    }//GEN-LAST:event_btn_inserirEstoqueActionPerformed

    private void txt_codigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoProdutoActionPerformed

    }//GEN-LAST:event_txt_codigoProdutoActionPerformed

    private void btn_mostraInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostraInfoActionPerformed
        // TODO add your handling code here:

        if (!txt_codigoProduto.getText().isEmpty()) {
            ProdutoDAO daoProduto = new ProdutoDAO();
            int codigo = Integer.parseInt(txt_codigoProduto.getText());
            Produto produto = daoProduto.getInfoProduto(codigo);

            lbl_nome.setText("Nome: " + produto.getNomeProduto());
            lbl_preco.setText("Preco: R$ " + produto.getPreco());
            lbl_qtdEstoque.setText("Quantidade em Estoque Atual: " + produto.getQuantidadeEstoque());
        } else {
            JOptionPane.showMessageDialog(null, "O campo código não pode estar vazio.");
        }
    }//GEN-LAST:event_btn_mostraInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirEstoqueProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirEstoqueProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirEstoqueProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirEstoqueProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InserirEstoqueProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inserirEstoque;
    private javax.swing.JButton btn_mostraInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_preco;
    private javax.swing.JLabel lbl_qtdEstoque;
    private javax.swing.JFormattedTextField txt_addEstoque;
    private javax.swing.JTextField txt_codigoProduto;
    // End of variables declaration//GEN-END:variables
}
