/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.GeradorPdf;
import controller.Venda;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.VendaDAO;

/**
 *
 * @author gustavo
 */
public class RelatorioMensal extends javax.swing.JFrame {

    /**
     * Creates new form SelecionarData
     */
    public RelatorioMensal() {
        initComponents();
        this.alinhaCelulas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jPanel1 = new javax.swing.JPanel();
        btn_mostrarVendas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_vendas = new javax.swing.JTable();
        btn_salvarRelatorio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        num_mes = new com.toedter.calendar.JMonthChooser();
        num_ano = new com.toedter.calendar.JYearChooser();
        txt_totalVendasVar = new javax.swing.JLabel();
        txt_totalVendasFix = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(234, 211, 161));

        btn_mostrarVendas.setText("Mostrar Vendas");
        btn_mostrarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarVendasActionPerformed(evt);
            }
        });

        tbl_vendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Venda", "Valor", "Data"
            }
        ));
        jScrollPane1.setViewportView(tbl_vendas);
        if (tbl_vendas.getColumnModel().getColumnCount() > 0) {
            tbl_vendas.getColumnModel().getColumn(1).setResizable(false);
            tbl_vendas.getColumnModel().getColumn(2).setResizable(false);
        }

        btn_salvarRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf1.png"))); // NOI18N
        btn_salvarRelatorio.setText("  Salvar Relatório");
        btn_salvarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarRelatorioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Relatório Mensal");

        txt_totalVendasVar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_totalVendasVar.setText("R$ ");

        txt_totalVendasFix.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_totalVendasFix.setText("Total de Vendas:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_mostrarVendas)
                    .addComponent(btn_salvarRelatorio)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(num_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(num_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_totalVendasFix, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_totalVendasVar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(num_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_mostrarVendas)
                        .addGap(52, 52, 52)
                        .addComponent(txt_totalVendasFix, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_totalVendasVar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(btn_salvarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mostrarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarVendasActionPerformed

        this.preencherTabela();

    }//GEN-LAST:event_btn_mostrarVendasActionPerformed

    private void btn_salvarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarRelatorioActionPerformed
        
        GeradorPdf geradorPdf = new GeradorPdf();
        try {
            geradorPdf.salvarPdfVendaMensal(num_mes.getMonth() + 1, num_ano.getYear());
        } catch (IOException ex) {
            Logger.getLogger(RelatorioMensal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_salvarRelatorioActionPerformed

    private void preencherTabela() {
        
        SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
        VendaDAO daoVenda = new VendaDAO();

        DefaultTableModel dtmVendas = (DefaultTableModel) tbl_vendas.getModel();
        dtmVendas.setRowCount(0);
        for (Venda vendaTemp : daoVenda.getVendasMensais(num_mes.getMonth() + 1, num_ano.getYear())) {
            int idVenda = vendaTemp.getIdVenda();
            String valorVenda = String.format("%.2f", vendaTemp.getValorVenda()).replace(".", ",");
            String dataVenda = f.format(vendaTemp.getDataVenda());
            Object[] dados = {
                idVenda,
                valorVenda,
                dataVenda
            };

            dtmVendas.addRow(dados);
        }
        this.atualizaVendaFinal();

    }

    private void alinhaCelulas() {
        DefaultTableCellRenderer cellRender = new DefaultTableCellRenderer();
        cellRender.setHorizontalAlignment(SwingConstants.CENTER);

        for (int numCol = 0; numCol < tbl_vendas.getColumnCount(); numCol++) {
            tbl_vendas.getColumnModel().getColumn(numCol).setCellRenderer(cellRender);
        }
    }

    private void atualizaVendaFinal() {

        double valorTotal = 0;

        for (int i = 0; i < tbl_vendas.getRowCount(); i++) {
            String strValorLinha = (String) tbl_vendas.getModel().getValueAt(i, 1);
            double valorLinha = Double.parseDouble(strValorLinha.replace(",", "."));
            valorTotal += valorLinha;
        }

        String strValorTotal = String.format("%.2f", valorTotal);
        txt_totalVendasVar.setText("R$  " + strValorTotal);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioMensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioMensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioMensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioMensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioMensal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mostrarVendas;
    private javax.swing.JButton btn_salvarRelatorio;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JYearChooser num_ano;
    private com.toedter.calendar.JMonthChooser num_mes;
    private javax.swing.JTable tbl_vendas;
    private javax.swing.JLabel txt_totalVendasFix;
    private javax.swing.JLabel txt_totalVendasVar;
    // End of variables declaration//GEN-END:variables
}
