/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Cliente;
import controller.GeradorPdf;
import controller.Venda;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.ClienteDAO;

/**
 *
 * @author gustavo
 */
public class VizualizaVendasPorCliente extends javax.swing.JFrame {

    /**
     * Creates new form VizualizacaoVendasPorCliente
     */
    public VizualizaVendasPorCliente(String nomeCliente) {
        initComponents();
        this.preencherTabela(nomeCliente);
        this.preencheDados(nomeCliente);
        this.alinhaCelulas();
        this.atualizaValorTotal();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_VendasPorCliente = new javax.swing.JTable();
        btn_salvarRelatorio = new javax.swing.JButton();
        lbl_nome = new javax.swing.JLabel();
        lbl_cpf = new javax.swing.JLabel();
        lbl_endereco = new javax.swing.JLabel();
        lbl_telefone = new javax.swing.JLabel();
        txt_valorTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(234, 211, 161));

        tbl_VendasPorCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idVenda", "Valor", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_VendasPorCliente);

        btn_salvarRelatorio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_salvarRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf1.png"))); // NOI18N
        btn_salvarRelatorio.setText("  Salvar Relatório");
        btn_salvarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarRelatorioActionPerformed(evt);
            }
        });

        lbl_nome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_nome.setText("Nome:");

        lbl_cpf.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_cpf.setText("CPF:");

        lbl_endereco.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_endereco.setText("Endereço:");

        lbl_telefone.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_telefone.setText("Telefone:");

        txt_valorTotal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_valorTotal.setText("Valor Total: RS 0000,00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_salvarRelatorio)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_endereco))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_cpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_telefone, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))))
                    .addComponent(txt_valorTotal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(lbl_cpf))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_endereco)
                    .addComponent(lbl_telefone))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btn_salvarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preencherTabela(String nomeCliente) {
        DefaultTableModel dtmVendasCliente = (DefaultTableModel) tbl_VendasPorCliente.getModel();
        dtmVendasCliente.setRowCount(0);

        ArrayList<Venda> listaVendas = new ArrayList<>();
        ClienteDAO daoCliente = new ClienteDAO();
        listaVendas = daoCliente.getVendaCliente(nomeCliente);
        SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");

        for (Venda venda : listaVendas) {

            Object[] dados = {
                venda.getIdVenda(),
                "R$ " + String.format("%.2f", venda.getValorVenda()),
                f.format(venda.getDataVenda())
            };

            dtmVendasCliente.addRow(dados);

        }
    }

    private void alinhaCelulas() {
        DefaultTableCellRenderer cellRender = new DefaultTableCellRenderer();
        cellRender.setHorizontalAlignment(SwingConstants.CENTER);
        for (int numCol = 0; numCol < tbl_VendasPorCliente.getColumnCount(); numCol++) {
            tbl_VendasPorCliente.getColumnModel().getColumn(numCol).setCellRenderer(cellRender);
        }
    }

    private void preencheDados(String nomeCliente) {
        ClienteDAO daoCliente = new ClienteDAO();
        Cliente clienteTemp = daoCliente.getInfoCliente(nomeCliente);
        lbl_nome.setText("Nome: " + clienteTemp.getNome());
        if (!clienteTemp.getEndereco().isEmpty()) {
            lbl_endereco.setText("Endereço: " + clienteTemp.getEndereco());
        } else {
            lbl_endereco.setText("Endereço: -");
        }
        if(clienteTemp.getCpf()!=0){
            lbl_cpf.setText("CPF: " + clienteTemp.getCpf());
        } else{
            lbl_cpf.setText("CPF: -");
        }
        if(clienteTemp.getTelefone() != 0){
            lbl_telefone.setText("Telefone: " + clienteTemp.getTelefone());
        } else{
            lbl_telefone.setText("Telefone: -");
        }
    }
    
    private void atualizaValorTotal() {
        double valorTotal = 0;
        for (int i = 0; i < tbl_VendasPorCliente.getRowCount(); i++) {
            String strValorLinha = (String) tbl_VendasPorCliente.getModel().getValueAt(i, 1);
            double valorLinha = Double.parseDouble(strValorLinha.replace(",", ".").replace("R$ ", ""));
            valorTotal += valorLinha;
        }

        String strValorTotal = String.format("%.2f", valorTotal);
        txt_valorTotal.setText("R$  " + strValorTotal);
    }


    private void btn_salvarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarRelatorioActionPerformed
        GeradorPdf geradorPdf = new GeradorPdf();
        String strValorTotal = txt_valorTotal.getText();
        String nomeCliente = lbl_nome.getText().replace("Nome: ", "");
        try {
            geradorPdf.salvarVendasPorCliente(nomeCliente, strValorTotal);
        } catch (IOException ex) {
            Logger.getLogger(VizualizaVendasPorCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_salvarRelatorioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salvarRelatorio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JLabel lbl_endereco;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_telefone;
    private javax.swing.JTable tbl_VendasPorCliente;
    private javax.swing.JLabel txt_valorTotal;
    // End of variables declaration//GEN-END:variables
}
